---
version: 2
updates: 
  - package-ecosystem: "gomod"
    groups:
      golang-security-update:
        applies-to: security-updates
    labels:
      - "Kind/Dependency"
      - "Kind/Security"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
